---
title: "changepoints"
author: ""
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    social: menu
    source_code: embed
    vertical_layout: scroll
    navbar:
      - { icon: "fa-twitter", href: "https://twitter.com/zaidrdnxla", align: right }
      - { icon: "fa-github", href: "https://github.com/alxndrdiaz", align: right }
      - { icon: "fa-linkedin", href: "https://www.linkedin.com/in/alexander-ramos-d%C3%ADaz-3063891aa", align: right }
    theme: 
      version: 4
      bootswatch: cosmo
runtime: shiny
---

```{r setup, include=FALSE}


# libraries
suppressPackageStartupMessages({
library(flexdashboard)
library(knitr)
library(shiny) 
library(changepoint)
library(changepoint.np)
library(dplyr)
library(ggplot2) 
library(plotly)
library(tsbox)
library(scales)
library(smooth)
})


# functions to process and visualize time series and changepoints
#-------------------------------------------------------------------------------

##  datcpt : changepoint results object 
##  tsdata : dataframe or time.series object, 1st column: observations, second column: signal  

## (1.1) functions associated with cpt.mean for dataframe/time-series with float or integer / date  values   

gather_seg_cmean <- function(datcpt){
  require(changepoint)
  where_cpt <- cpts(datcpt) 
  i_x  <-  c(0,where_cpt)
  f_x  <-  datcpt@cpts
  i_y  <- datcpt@param.est$mean
  f_y  <- datcpt@param.est$mean
  sgt_data <- data.frame(i_x , f_x , i_y , f_y ,  row.names = NULL)
  names(sgt_data) <- c("ix", "fx", "iy", "fy")
  return(sgt_data) }

gather_seg_cmean_ts <- function(tsdata, datcpt){
  require(changepoint); require(tsbox)
  tsdata <- ts_df(tsdata)
  where_cpt <- cpts(datcpt) 
  i_x  <-  c(1,where_cpt)
  f_x  <-  datcpt@cpts
  i_y  <- datcpt@param.est$mean
  f_y  <- datcpt@param.est$mean
  sgt_data <- data.frame(i_x , f_x , i_y , f_y ,  row.names = NULL)
  names(sgt_data) <- c("ix", "fx", "iy", "fy")
  sgt_data$ix <- tsdata[ sgt_data$ix , 1 ]
  sgt_data$fx <- tsdata[ sgt_data$fx , 1 ]
  return(sgt_data) }

gather_arrow_cmean <- function(datcpt){
  require(changepoint)
  where_cpt <- cpts(datcpt) 
  mcpts <- datcpt@param.est$mean
  arrow_start_y <- c( 1:(length(mcpts)-1) ) 
  arrow_end_y <- c( 2:length(mcpts) )
  arrow_data <- data.frame(where_cpt, mcpts[arrow_start_y], where_cpt, mcpts[arrow_end_y])
  names(arrow_data) <- c("ax","ay","bx","by")
  return(arrow_data) }

gather_arrow_cmean_ts <- function(tsdata, datcpt){
  require(changepoint); require(tsbox)
  tsdata <- ts_df(tsdata)
  where_cpt <- cpts(datcpt) 
  mcpts <- datcpt@param.est$mean
  arrow_start_y <- c( 1:(length(mcpts)-1) ) 
  arrow_end_y <- c( 2:length(mcpts) )
  arrow_data <- data.frame(where_cpt, mcpts[arrow_start_y], where_cpt, mcpts[arrow_end_y])
  names(arrow_data) <- c("ax","ay","bx","by")
  arrow_data$ax <- tsdata[ arrow_data$ax , 1 ]
  arrow_data$bx <- tsdata[ arrow_data$bx , 1 ]
  return(arrow_data) }

get_seglengths <- function(datcpt){
  require(changepoint)
  nsegments <- length( seg.len(datcpt) )
  seg_lengths <- as.data.frame( seg.len(datcpt) )
  colnames(seg_lengths) <- paste('n = ', as.character(nsegments), " segments, lengths:", sep='')
  rownames(seg_lengths) <- NULL
  return(seg_lengths)
}

convert_cpts_to_time <- function(tsdata, datcpt){
  require(changepoint)
  time_ctps <- tsdata[cpts(datcpt),1]
  return(time_ctps) }

gather_cmean_summary <- function(datarrows,epsilon=1e-4,ts=FALSE, date_as="%Y-%m-%d"){
cmsummary <- data.frame(
  changepoint = datarrows$ax, 
  log10_difference = log10( epsilon + abs(datarrows$by) )  - log10( epsilon +  abs(datarrows$ay) ), 
  row.names = NULL)
  if(ts==TRUE){
    cmsummary$changepoint <- as.character( format(cmsummary$changepoint,format=date_as) ) 
  }
  return(cmsummary) }

generate_cmplot <- function(tsdata, datcpt, xtime, ysignal, plotitle, curve_color, grid_color,cp_labels){
  if( class(tsdata) == "data.frame" ){  
  sgt_data <- gather_seg_cmean(datcpt = datcpt)
  arrow_data <- gather_arrow_cmean(datcpt = datcpt)
  if(cp_labels==TRUE){
    cplabels=as.character(arrow_data$ax)
  }else if(cp_labels==FALSE){
    cplabels=NULL }
  cmplot  <- ggplot(data = tsdata, aes(x=tsdata[,1], y=tsdata[,2]) ) +
    geom_line(color=curve_color, lwd=0.8) +
    geom_segment(data=sgt_data, aes(x=ix, y=iy, xend=fx, yend=fy), lwd=0.85) +
    geom_segment(data=arrow_data, aes(x=ax,y=ay,xend=bx,yend=by), lwd=0.85, arrow=arrow(ends='last', length=unit(4.75, 'mm'), angle=15, type='closed' ) ) +
    scale_x_continuous(sec.axis = sec_axis(~ ., breaks=arrow_data$ax, labels = cplabels ) ) +
    labs(title=plotitle,
         x= paste("[ ", xtime, " ]", sep="") , 
         y=ysignal) +
    theme(  axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1), 
            panel.background = element_rect(fill = 'white', colour = 'black'), 
            panel.grid.major = element_line(colour = grid_color) )   } 
   else if ( class(tsdata) == "ts" ){
     require(tsbox); require(scales)
     sgt_data <- gather_seg_cmean_ts(tsdata, datcpt = datcpt)
     arrow_data <- gather_arrow_cmean_ts(tsdata = tsdata, datcpt = datcpt)
     if(cp_labels==TRUE){
       datelabels=scales::label_date_short()
     }else if(cp_labels==FALSE){
       datelabels=NULL }
     cmplot  <- ts_ggplot(tsdata) +
       geom_line(color="skyblue", lwd=0.8) +
       geom_segment(data =  sgt_data, aes(x=ix, y=iy, xend=fx, yend=fy), lwd=0.85) +
       geom_segment(data=arrow_data, aes(x=ax,y=ay,xend=bx,yend=by), lwd=0.85, arrow=arrow(ends='last', length=unit(4.75, 'mm'), angle=15, type='closed' ) ) +
       scale_x_date(sec.axis = sec_axis(~ ., breaks=arrow_data$ax, labels=datelabels )  ) +
       labs(title=plotitle,
            x= paste("[ ", xtime, " ]", sep="") , 
            y=ysignal) +
       theme(  axis.text.x = element_text(angle = 0, vjust = 0.5, hjust=1), 
               panel.background = element_rect(fill = 'white', colour = 'black'), 
               panel.grid.major = element_line(colour = grid_color) )  }
  return(cmplot)   }
 
 
## (1.2) functions associated with cpt.var for dataframe/time-series with float or integer / date  values   
 
gather_cvar_summary <- function(tsdata, datcpt, epsilon=1e-4, ts=FALSE, date_as="%Y-%m-%d"){
   var_cpts <- convert_cpts_to_time(tsdata=tsdata, datcpt=datcpt)
    cvarsummary <- data.frame(
     changepoint = var_cpts, 
     variance_difference = diff( log10( epsilon + abs(datcpt@param.est$variance) )  ), 
     row.names = NULL)
    if(ts==TRUE){
      cvarsummary$changepoint <- as.character( format(cvarsummary$changepoint,format=date_as) ) 
    }
   return(cvarsummary) }
 
# works for ts or dataframe with dates in the x axis
generate_cvplot <- function(tsdata, datcpt, xtime, ysignal, plotitle, curve_color, grid_color, cp_labels){
     require(scales)
     time_ctps <- convert_cpts_to_time(tsdata=tsdata, datcpt=datcpt)
     if(cp_labels==TRUE){
       datelabels=scales::label_date_short()
     }else if(cp_labels==FALSE){
       datelabels=NULL }
     cmplot  <- ts_ggplot(tsdata) +
       geom_line(color=curve_color, lwd=0.85) +
       geom_vline(xintercept = time_ctps) + 
       scale_x_date(sec.axis = sec_axis(~ ., breaks=time_ctps, labels=datelabels  )  ) +
       labs(title=plotitle,
            x= paste("[ ", xtime, " ]", sep="") , 
            y=ysignal) +
       theme(  axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), 
               panel.background = element_rect(fill = 'white', colour = 'black'), 
               panel.grid.major = element_line(colour = grid_color) )    
   return(cmplot)   }

#-------------------------------------------------------------------------------


# code chunks for each tab
#-------------------------------------------------------------------------------

# [0] normal/gaussian distribution example, N=200 points (front page)
## generate random dataset
set.seed(1)
m1=c(rnorm(100,0,1),rnorm(100,5,1))
m1_data <- as.data.frame(m1)
m1_data$obs <- as.integer( c(1:length(m1))  )
m1_data <- m1_data[, c(2,1)]
##  default values of a single change (method="AMOC") 
m1amoc <- cpt.mean(m1_data[,2])
## arrows to use with plotly
m1_arrows <- gather_arrow_cmean(datcpt = m1amoc)
## changepoint plot 
m1plot <- generate_cmplot(tsdata = m1_data, datcpt = m1amoc, 
                                 xtime='Time', ysignal='X', 
                                 plotitle='Normal simulated data, N = 200 points', 
                                 curve_color='tomato', grid_color='white', 
                                 cp_labels=TRUE)


# [1] using sim.ssarima() to generate a plotly with N observations/points and summary results
## SSARIMA simulated data
NSSARIMA_data <- function(Npoints){
ssimulation <- sim.ssarima(frequency=10, obs=Npoints, nsim=1)
return(ssimulation)
}
# changeplot plotly
NSSARIMA_plotly <- function(simdata){
ssim_pm <- cpt.mean(simdata$data,test.stat='Normal',method='BinSeg',Q=10,penalty="BIC")
simdata <- as.data.frame(simdata$data)
simdata$obs <- as.integer( rownames(simdata) )
simdata <- simdata[, c(2,1)]
ssim_ctpsplot <- generate_cmplot(tsdata=simdata, datcpt=ssim_pm,xtime='time units',
                                 ysignal = 'signal', 
                                 plotitle='Simulated data, model: ssarima()', 
                                 curve_color='pink', grid_color='lightgray', cp_labels=TRUE)
ssim_arrows <- gather_arrow_cmean(datcpt = ssim_pm)
ggplotly(ssim_ctpsplot) %>% 
  add_annotations( x=ssim_arrows$bx, y=ssim_arrows$by, ax=ssim_arrows$ax, ay=ssim_arrows$ay,
                   xref='x', yref='y', axref='x', ayref='y',
                   text='', showarrow=TRUE, 
                   arrowhead=2, arrowsize=3, arrowwidth=1, arrowcolor='black') 
}
## SSARIMA changepoint parameters summary 
NSSARIMA_summary <- function(simdata){
ssim_pm <- cpt.mean(simdata$data,test.stat='Normal',method='BinSeg',Q=10,penalty="BIC")
capture.output( summary(ssim_pm) )
}
## cmean_summary
NSSARIMA_cmean_summary <- function(simdata){
ssim_pm <- cpt.mean(simdata$data,test.stat='Normal',method='BinSeg',Q=10,penalty="BIC")
simdata <- as.data.frame(simdata$data)
simdata$obs <- as.integer( rownames(simdata) )
simdata <- simdata[, c(2,1)]
ssim_arrows <- gather_arrow_cmean(datcpt = ssim_pm)
gather_cmean_summary(datarrows = ssim_arrows, epsilon=1e-4, ts=FALSE)
}
## segment lengths
NSSARIMA_segments <- function(simdata){
ssim_pm <- cpt.mean(simdata$data, test.stat='Normal',method='BinSeg',Q=10,penalty="BIC")
get_seglengths(datcpt = ssim_pm)
}


# [2] Nile data 
# loads example dataset from changepoint
data(Nile)
# following the tutorial, this would be the correct approach to estimate changepoints
pm_Nile <- cpt.mean(Nile,pen.value=1,penalty='Manual',test.stat='CUSUM')
## arrows to use with plotly
nile_arrows <- gather_arrow_cmean_ts(tsdata = Nile, datcpt = pm_Nile)
## changepoint plot
nile_ctplot <- generate_cmplot(tsdata=Nile, datcpt=pm_Nile, 
                                 xtime="year", ysignal="[1e8 cubic meters]", 
                                 plotitle='Flow of the River Nile 1871-1970', 
                                 curve_color='skyblue', grid_color='lightgray',cp_labels=TRUE)


# [2] Nile data 
# loads example dataset from changepoint
data(ftse100)
colnames(ftse100) <- c('date','return')
# following the tutorial, this would be the correct approach to estimate changepoints
pv_ftse100 <- cpt.var(ftse100[,2],method='PELT',penalty='Manual',pen.value='1.5*log(n)')
## changepoint plot
yahoo <- 'Yahoo! finance data'
yahoo_ctpsplot <- generate_cvplot(tsdata=ftse100, datcpt=pv_ftse100, xtime='date', ysignal='daily return', 
                                 plotitle=yahoo, curve_color='lightgreen', grid_color='white',  cp_labels=FALSE)
## convert changepoint positions to dates
yahoo_dates <- convert_cpts_to_time(tsdata = ftse100, datcpt=pv_ftse100); 

#-------------------------------------------------------------------------------


```

What are changepoints?
=======================================================================

Column
-----------------------------------------------------------------------

### 

**What are changepoints?**

"Simply put, a changepoint is an instance in time where the statistical properties before and after this time point differ. With potential changes naturally occurring in data and many statistical methods assuming a *'no change'* setup, changepoint analysis is important in both applied and theoretical statistics" [Introduction to optimal changepoint detection algorithms by Rebecca Killick](https://tdhock.github.io/change-tutorial/RK-CptWorkshop.html). We provide a few examples of change point estimation using [changepoint R library](https://cran.r-project.org/web/packages/changepoint/index.html). This library implements various algorithms for changepoint search, however it does not include uncertainty estimations. There are are other libraries that can be used for the same task, see for example: [An overview of change point packages in R by Jonas Kristoffer Lindeløv](https://lindeloev.github.io/mcp/articles/packages.html).

If you are interested in problems that involve a time-dependent signal want to know if there are points for which the mean signal increases or decreases then change point estimation might be a good approach to try. The changepoint library provides algorithms to search change points associated both with changes in mean and variance (*cpt.mean* and  *cpt.var* respectively). Here we only will explore two examples using *cpt.mean* (simulated data, Nile dataset from changepoint library) and one *cpt.var* example (Yahoo! finance dataset also from changepoint library). For the simulated data we used the *sim.ssarima* function from [smooth library](https://cran.r-project.org/web/packages/smooth/index.html), this function uses a variation of the  [autoregressive integrated moving average (ARIMA) model](https://en.wikipedia.org/wiki/Autoregressive_integrated_moving_average) called [State-space ARIMA](https://cran.r-project.org/web/packages/smooth/vignettes/simulate.html) to simulate one or more [time series](https://en.wikipedia.org/wiki/Time_series).    

An estimation of changepoints in the mean is shown below for a simulated normal dataset of N = 200 points. The vertical line are segments and the arrow indicates the changepoint. In the examples the values for these results are also provided, additionally the change between the start and final point for each changepoint (arrow tail and arrow tip) is computed as follows: difference = log10(tip) - log10(tail). A similar definition is used for variance when a changepoint is detected between a previous and current variance values: difference = log10(current) - log10(previous).

References:

[1] Killick, R. & Eckley, I. A. changepoint : An R Package for Changepoint Analysis. J. Stat. Soft. 58, (2014).[http://dx.doi.org/10.18637/jss.v058.i03](http://dx.doi.org/10.18637/jss.v058.i03).

### Example: cpt.mean applied to normal simulated data, N = 200 points. 
```{r}

fillCol( width = "100%", height = "100%", flex = c(1,1,5),
plotlyOutput("m1plot", height="100%")
)

# changepoints plot
output$m1plot <- renderPlotly(
ggplotly(m1plot) %>% 
add_annotations( x=m1_arrows$bx, y=m1_arrows$by, ax=m1_arrows$ax, ay=m1_arrows$ay,
                   xref='x', yref='y', axref='x', ayref='y',
                   text='', showarrow=TRUE, 
                   arrowhead=2, arrowsize=3, arrowwidth=1, arrowcolor='black')
)


```


Simulated data
=======================================================================


Column 
-----------------------------------------------------------------------
### sim.ssarima()  simulated data 
```{r}

# use the selected number of points top simulate the data
npoints <- reactive( as.integer(input$npoints) ) 


simulated_data <- reactive(
  NSSARIMA_data( Npoints = npoints() ) 
)
 
selectInput("npoints", label = "Number of observations", 
 choices = list("100"=100, "250"=250, "500"=500, "1000"=1000, "2500"=2500, "5000"=5000, "10000"=10000), 
    selected = 10000)
  

fillRow( width = "100%", height = "100%", flex = c(1,1,5),
    plotlyOutput("simplot", height="100%")
)


# plotly from function
output$simplot <- renderPlotly(
  NSSARIMA_plotly(simdata = simulated_data()  )
)

```  


### Algorithm, parameters, and results 
```{r}

renderTable( 
  NSSARIMA_summary( simdata = simulated_data()  ), 
  colnames=FALSE
)

renderTable(
  { NSSARIMA_cmean_summary( simdata = simulated_data() ) }, 
  align='l'
)

renderTable(
  {  NSSARIMA_segments( simdata = simulated_data() )  },
  align='l'
)
  


```


Nile dataset
=======================================================================

Column
-----------------------------------------------------------------------

### cpt.mean on Nile dataset 
Example dataset included in changepoint library:
```{r}

fillCol( width = "100%", height = "100%", flex = c(1,1,5),
plotlyOutput("nileplot", height="100%")
)

# changepoints plot
output$nileplot <- renderPlotly(
ggplotly(nile_ctplot) %>%
add_annotations( x=as.numeric(nile_arrows$bx), ax=as.numeric(nile_arrows$ax), 
                 y=nile_arrows$by, ay=nile_arrows$ay,
                 xref='x', yref='y', axref='x', ayref='y', text='', showarrow=TRUE,
                 arrowhead=2, arrowsize=3, arrowwidth=1, arrowcolor='black')
)
```  


### Algorithm, parameters, and results 
```{r}

renderTable(
capture.output( summary(pm_Nile) ), 
colnames=FALSE
)

renderTable(
  {gather_cmean_summary(datarrows = nile_arrows, epsilon=1e-4, ts=TRUE, date_as="%Y")}, 
  align='l'
  )

renderTable(
  {get_seglengths(datcpt = pm_Nile)}, 
  align='l'
)

```


Yahoo! finance dataset
=======================================================================

Column
-----------------------------------------------------------------------

### cpt.var on Yahoo! finance dataset 
Example dataset included in changepoint library:
```{r}

fillCol( width = "100%", height = "100%", flex = c(1,1,5),
plotlyOutput("yahooplot", height="100%")
)

# changepoints plot
output$yahooplot <- renderPlotly(
ggplotly(yahoo_ctpsplot) %>%
add_segments(x=as.numeric(yahoo_dates), xend=as.numeric(yahoo_dates), 
             y=min(ftse100[,2]) , yend=max(ftse100[,2]), color=I('black'), 
             text=yahoo_dates, line=list(linewidth=0.15) ) 
)
```  


### Algorithm, parameters, and results 
```{r}

renderTable(
  capture.output( summary(pv_ftse100) ), 
  colnames=FALSE
)

renderTable({
gather_cvar_summary(tsdata=ftse100, datcpt=pv_ftse100, epsilon=1e-4, ts=TRUE, date_as="%Y-%m-%d")
})
  
```
